### ISSUE TITLE
consult the question of ICP

### ISSUE THREAD

**Issue by 1805344946ts** [agnivsen/icp#5]
Hello author, I am studying ICP algorithm recently and I have learned a lot from your work. I have some questions. I cannot understand the mean of output sucn as `print (np.transpose(initial))` in basicICP.py. If I want to get R,what can I do please?  I'm looking forward to hearing you.Thank you!

**Comment by agnivsen** [comment]
Hi,

I do not understand your question, what is 'R' ? Which line in the code are you referring to?

More importantly, is your question actually an 'issue' with the code? Or do you need some general information about ICP? In the later case, please send me an e-mail and allow me to close this issue. However, if this is actually about an issue, I would need more details please.

Regards,
Agniva

**Comment by agnivsen** [comment]
Hi @1805344946ts, 

I am going to close this issue, since I do not fully understand the issue and without some additional input from your end, I am unable to proceed with any possible resolution. Please open another issue when/if you think it is needed. For additional input, please feel free to drop me an e-mail.

Regards,
Agniva
